### PR TITLE
Added discogs_marketplace_price_suggestions

### PR DESCRIPTION
**Pull request by alesaccoia**
Hi, I have added this handy marketplace method to get suggested prices. Works well with vinyl grading

### CODE REVIEW

**Review by ewenme — CHANGES_REQUESTED** [review]
nice! works great, just wonder if the function name is a bit on the large size. How about `discogs_mkt_price_suggest`?

**Comment by alesaccoia** [comment]
Sounds good to me!

**Comment by alesaccoia** [comment]
Done, that should be it. Sorry it took so long!

**Comment by alesaccoia** [comment]
Committed and re-opened

**Comment by ewenme** [comment]
nice one! ill add u as an author to the description file 👍

**Comment by alesaccoia** [comment]
nice! will cite the library in a public dashboard I'm preparing if I finish it. keep u posted!

**Pull request merged**
